# Generated by Django 5.2.1 on 2025-06-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enventario', '0002_produto_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtoestoque',
            name='data_de_validade',
            field=models.DateField(blank=True, null=True, verbose_name='Data de validade:'),
        ),
    ]
