# Generated by Django 5.2.1 on 2025-06-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enventario', '0003_alter_produtoestoque_data_de_validade'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='fisioterapia',
            field=models.BooleanField(default=False, help_text='Marque se o produto for utilizado na fisioterapia.', verbose_name='Produto de fisioterapia?'),
        ),
    ]
