# Generated by Django 5.2.1 on 2025-06-03 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_retirada', models.PositiveIntegerField(verbose_name='Quantidade retirada')),
                ('data_retirada', models.DateTimeField(auto_now_add=True, verbose_name='Data da retirada')),
                ('fisioterapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Fisioterapeuta')),
                ('produto_estoque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enventario.produtoestoque', verbose_name='Produto do Estoque')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'db_table': 'transacao',
            },
        ),
    ]
