# Generated by Django 5.2.1 on 2025-06-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='destino',
            field=models.CharField(choices=[('SUS', 'SUS'), ('CONSULTORIO', 'Consultório')], default='sus', max_length=20, verbose_name='Destino'),
            preserve_default=False,
        ),
    ]
