# Generated by Django 5.2.1 on 2025-06-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacao', '0002_transacao_destino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='destino',
            field=models.CharField(choices=[('SUS', 'SUS'), ('CONSULTORIO', 'Consultório'), ('Clinica', 'Clínica')], max_length=20, verbose_name='Destino'),
        ),
    ]
